imports:
    - { resource: services/resolver.yaml }
    - { resource: services/twig.yaml }

##
## Keep this file empty.
## For better organization put your services grouped in services/ directory.
##
