services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    Ibexa\Platform\Assets\Event\Subscriber\AssetsInstallCommandSubscriber:
        arguments:
            $projectDir: '%kernel.project_dir%'
        tags: ['kernel.event_subscriber']
